name: Build Wheel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11.3]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SDL
        uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 2-latest
          version-sdl-image: 2-latest

#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install wheel
#
#      - name: Install SDL2
#        if: startsWith(matrix.os, 'ubuntu')
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
#
#      - name: Install SDL2
#        if: startsWith(matrix.os, 'macos')
#        run: |
#          brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf

      - name: Install SDL2
        if: startsWith(matrix.os, 'windows')
        run: |
          choco install sdl2 sdl2_image sdl2_mixer sdl2_ttf -y

      - name: Build wheel
        run: |
          python setup.py bdist_wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/*.whl
